[package]
name = "music_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
# rusqlite = {version="0.28.0", features=["bundled"]}
rusqlite = {version="0.28.0"}
serde = {version="1.0.152", features=["derive"]}
serde_json = "1.0.91"
